[build.environment]
	NPM_FLAGS = "--version"
	NODE_VERSION = "16"

[build]
	publish = "dist"
	command = "npx nuxt build"
  /# command = "npx nuxi generate" for ssg

[[redirects]]
	from = "/*"
	to = "/index.html"
	status = 200